services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Service for processing large batches of messages
  batch_processor:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./scripts:/app/scripts
    command: python scripts/batch_processor.py
    depends_on:
      - api

  # Service for local development
  test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    command: pytest -v
    depends_on:
      - api